name: Update gist with PlayStation stats
on:
  schedule:
    - cron: "0 23 * * 0"
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update gist
        uses: Swilder-M/playstation-box@master
        env:
          PSN_NPSSO: ${{ secrets.PSN_NPSSO }}
          PSN_ACCESS_TOKEN: ${{ secrets.PSN_ACCESS_TOKEN }}
          PSN_REFRESH_TOKEN: ${{ secrets.PSN_REFRESH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
